Develop
junseok-seo/git-test pull request #3
Opened 2020-08-07 03:41 UTC by Limjaewoo-kor

요청합니다.

2020-08-07 04:16 UTC, junseok-seo commented on index.html
> +            <a href="#" style="font-weight: bold;">연합뉴스</a>
연합뉴스 대신에 중앙일보로 바꿔주세요

2020-08-07 04:16 UTC, junseok-seo requested changes
INDEX.HTML 수정 요망

2020-08-07 06:25 UTC, Limjaewoo-kor commented on index.html
> +            <a href="#" style="font-weight: bold;">연합뉴스</a>
네 알겟습니다

2020-08-07 10:18 UTC, junseok-seo requested changes
지금 실습 파일들이 리파지토리 루트로 나와 있는데
본인 이름 폴더 만들고 그 안에 파일들을 다 넣어주세요

2020-08-07 11:17 UTC, Limjaewoo-kor commented
제 이름 리포지토리 만들어서 옮겼습니다.

2020-08-07 13:31 UTC, Limjaewoo-kor commented
레포지토리를 새로 만들어서 옮기라는건줄 알고 새로운 레포지토리에 미러 했다가,
다시 기존 레포지토리에 폴더 만들었습니다.

2020-08-08 01:29 UTC, junseok-seo approved these changes

2020-08-08 01:31 UTC, junseok-seo commented on Limjaewoo/common
> +﻿임재우
지금 현재 develop 브랜치에 올라와있는 최신 common 파일에 이름 붙여서 반영해주세요~

2020-08-08 01:31 UTC, junseok-seo requested changes
common 파일 수정

2020-08-08 04:15 UTC, merged