Develop
junseok-seo/git-test pull request #5
Opened 2020-08-07 04:15 UTC by cheonghakim

확인을 해 주세요

2020-08-07 04:19 UTC, junseok-seo commented on naver/index.html
> +              <div class="realtime_news_item2">서울 전역 비가 많이와</div>
서울 전역 비가 많이와 -> 전국에 비가 펑펑와

변경해 주세요

2020-08-07 04:20 UTC, junseok-seo requested changes
index.html 수정 요망

2020-08-07 05:37 UTC, cheonghakim commented on naver/index.html
> +              <div class="realtime_news_item2">서울 전역 비가 많이와</div>
수정을 했습니다.

2020-08-07 10:19 UTC, junseok-seo requested changes
루트에 본인 이름의 폴더를 만든 후에 그 안에 
파일들을 넣어주세요~

2020-08-08 04:03 UTC, cheonghakim commented on naver/index.html
> +              <div class="realtime_news_item2">서울 전역 비가 많이와</div>
디렉토리를 변경했습니다.

2020-08-08 04:16 UTC, merged